sign-commit = false
upload-doc = false
pre-release-commit-message = "Release {{version}} ğŸ‰ğŸ‰"
pro-release-commit-message = "Start next development iteration {{version}}"
tag-message = "Release {{prefix}}{{version}}"
dev-version-ext = "dev"
tag-prefix = "v"
