sign-commit = false
upload-doc = false
pre-release-commit-message = "Release {{crate_name}} {{version}} ğŸ‰ğŸ‰"
pro-release-commit-message = "Start next {{crate_name}} development iteration {{version}}"
tag-message = "Release {{crate_name}} {{prefix}}{{version}}"
dev-version-ext = "dev"
