sign-commit = false
pre-release-commit-message = "Release {{version}} ğŸ‰ğŸ‰"
post-release-commit-message = "Start next development iteration {{version}}"
tag-message = "Release {{prefix}}{{version}}"
dev-version-ext = "dev"
tag-prefix = ""
consolidate-commits = true