# TemplateCIConfig { bench: BenchEntry(MatrixEntry { run: false, version: "nightly", install_commandline: None, commandline: "cargo bench" }), clippy: ClippyEntry(MatrixEntry { run: true, version: "stable", install_commandline: Some("rustup component add clippy"), commandline: "cargo clippy -- -D warnings" }), rustfmt: RustfmtEntry(MatrixEntry { run: true, version: "stable", install_commandline: Some("rustup component add rustfmt"), commandline: "cargo fmt -v -- --check" }), additional_matrix_entries: {}, cache: "cargo", os: "linux", dist: "xenial", versions: ["stable", "nightly"], test_commandline: "cargo test --verbose --all" }
version: "2.1"

executors:
  stable:
    docker:
      - image: liuchong/rustup:stable
  nightly:
    docker:
      - image: liuchong/rustup:nightly
  beta:
    docker:
      - image: liuchong/rustup:beta

commands:
  cargo_test:
    description: "Run `cargo test`"
    steps:
      - run:
          name: "Clean out rust-toolchain"
          command: "rm -f rust-toolchain"
      - run:
          name: "Toolchain debug info"
          command: "rustc --version"
      - run:
          name: Test
          command: "cargo test"

jobs:
  test:
    parameters:
      version:
        type: executor
    executor: << parameters.version >>
    steps:
      - checkout
      - cargo_test

  rustfmt:
    parameters:
      version:
        type: executor
    executor: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add rustfmt
      - run:
          name: Rustfmt
          command: cargo fmt -v -- --check

  clippy:
    parameters:
      version:
        type: executor
    executor: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add clippy
      - run:
          name: Clippy
          command: cargo clippy -- -D warnings

  bench:
    parameters:
      version:
        type: executor
    executor: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Bench
          command: cargo bench

  ci_success:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Success
          command: "echo yay"

workflows:
  continuous_integration:
    jobs:
      - test:
          name: test-stable
          version: stable
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - test:
          name: test-nightly
          version: nightly
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - rustfmt:
          version: stable
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - clippy:
          version: stable
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - ci_success:
          requires:
          - test-stable
          - test-nightly
          - rustfmt
          - clippy
